### ISSUE TITLE
CODE REVIEW

### ISSUE THREAD

**Issue by Amoshalt** [PolytechLyon/pattern-strategy-tardy-tp2-strategy#1]
Pourriez vous me donner un avis sur mon TP s'il vous plait.

**Comment by k33g** [comment]
Bonjour @Amoshalt 

J'aurais aimé que vous me fassiez quelque chose d'un peu plus long concernant **Votre avis sur le pattern Strategy**

Même remarque pour les 3 exemples de cas d'utilisation (en plus celui des véhicules fait partie de ceux que je donnais dans le README)

Les exercices sont bien expliqués

**Comment by Amoshalt** [comment]
Bonjour,

Je viens d'améliorer mon explication du pattern ainsi que revu les exemples.
Pourriez vous me dire si cela vous va quand vous aurez le temps.

Ps: Il me semblerait que j'avais oublié de vous assigner sur le TP Kebab kata le 4 avril, c'est maintenant fait, je m'en excuse, je pense que c'est la réponse pour laquelle que vous n'avez pas corrigé.
